#! /bin/csh -f
echo " "
echo " =>executing: run_rotation"
echo " "
#
# script for testing the "rotation.F" routines
#
#     options: (must choose only one of these)
#       -Dread_my_grid    : read in your own grid definition
#       -Dgenerate_a_grid : generate a grid based on USER INPUT
#                           in grids.F
#

set OPTIONS = '-Ddrive_rotation -Drot_grid -Dgenerate_a_grid'

set MOMpath = /net/rcp/MOM_3        # base model code
set WORK = TEMP_DIR                 # temp directory
set OUTPUT = `pwd`                  # directory holding run script
                                    # and output files

set error = false
if (! -r rotation.F) then
  echo '=>Error: "rotation.F" is not in this UPDATES directory'
  set error = true
endif

if (! -r grids.F) then
  echo '=>Error: "grids.F" is not in this UPDATES directory'
  set error = true
endif

if (! -r size.h) then
  echo '=>Error: "size.h" is not in this UPDATES directory'
  set error = true
endif

if ("$error" == "true") then
  exit
endif

echo "=>Grabbing sources from $MOMpath"
mkdir $WORK
set list = (stdunits.h derived_options.h coord.h util.F iomngr.F size_check.F)
foreach file ($list)
  cp $MOMpath/$file $WORK
end
cp rotation.F $WORK
cp grids.F $WORK
cp size.h $WORK
cd $WORK

echo "=>compiling..."
f90 $OPTIONS rotation.F

echo "=> running...results are being written to results_rotation"
a.out > $OUTPUT/results_rotation

cd $OUTPUT
/bin/rm -r $WORK

echo " "
echo "=> Done"

